import type { SheetMeeting } from "./lto";

export const SHEET: SheetMeeting = {
  "banner": "HRC HYDERABAD",
  "title": "HANDICAP ANALYSIS & FORM RATING (LTO)",
  "when": "19-09-2026 - HYD - SATURDAY - 6 CARD",
  "source": "IndiaRace racecard, previous runs with track, and published trackwork as of 18 Sep 2026.",
  "note": "LTO is last two completed starts. Figure = 100 - (pos-1)*6.5 - beaten*3.2, +14 for a win, short-price winners lifted. Speed RTG is last winning time plus beaten lengths, per 200m (lower is faster). First starters and runs beaten 25L+ show ###. Tissue is a 120% book, not official HRC odds. Results stay blank until after the race.",
  "races": [
    {
      "no": 1,
      "official": 101,
      "name": "The Rock Of Gibraltar Plate",
      "class": "Maiden / For Horses 3 Year Olds Only",
      "dist": "1200m",
      "distM": 1200,
      "time": "01:55 PM",
      "timeCode": "1.55",
      "code": "12mMDN",
      "field": 8,
      "runners": [
        {
          "cloth": 1,
          "draw": 3,
          "name": "BELLA'S TOUCH",
          "filly": false,
          "trainer": "Neelesh Rawal",
          "jockey": "M S Deora",
          "age": "3y b c",
          "wt": 56.0,
          "al": "",
          "bnc": null,
          "rtgCh": null,
          "l2": {
            "days": null,
            "card": "",
            "pos": "###",
            "odds": null,
            "btl": null,
            "lto": "###"
          },
          "l1": {
            "days": 14,
            "card": "76",
            "pos": 2,
            "odds": "20",
            "btl": 4.5,
            "lto": 84
          },
          "nty": 6.0,
          "open": 7.08,
          "tissue": "5/1",
          "rank": 3,
          "speed": 12.48,
          "track": 70,
          "distDelta": 100,
          "wtDelta": 0.0,
          "cls": "Maiden",
          "hcp": 0.0,
          "dp": 4,
          "days": 14,
          "tone": "pick"
        },
        {
          "cloth": 2,
          "draw": 7,
          "name": "CHANCED ONE",
          "filly": false,
          "trainer": "Magan Singh",
          "jockey": "D S Deora",
          "age": "3y b c",
          "wt": 56.0,
          "al": "",
          "bnc": null,
          "rtgCh": null,
          "l2": {
            "days": null,
            "card": "",
            "pos": "###",
            "odds": null,
            "btl": null,
            "lto": "###"
          },
          "l1": {
            "days": null,
            "card": "",
            "pos": "###",
            "odds": null,
            "btl": null,
            "lto": "###"
          },
          "nty": 17.0,
          "open": 20.06,
          "tissue": "16/1",
          "rank": 7,
          "speed": null,
          "track": 45,
          "distDelta": null,
          "wtDelta": null,
          "cls": "Maiden",
          "hcp": 0.0,
          "dp": null,
          "days": null,
          "tone": "plain"
        },
        {
          "cloth": 3,
          "draw": 4,
          "name": "FRENCH LIEUTENANT",
          "filly": false,
          "trainer": "L V R Deshmukh",
          "jockey": "Antony Raj S",
          "age": "3y b g",
          "wt": 56.0,
          "al": "",
          "bnc": 37,
          "rtgCh": 3,
          "l2": {
            "days": 27,
            "card": "53",
            "pos": 3,
            "odds": "1.9",
            "btl": 2.5,
            "lto": 77
          },
          "l1": {
            "days": 12,
            "card": "82",
            "pos": 2,
            "odds": "5",
            "btl": 1.5,
            "lto": 88
          },
          "nty": 4.0,
          "open": 4.72,
          "tissue": "3/1",
          "rank": 2,
          "speed": 12.32,
          "track": 75,
          "distDelta": -200,
          "wtDelta": 0.0,
          "cls": "Maiden",
          "hcp": 0.0,
          "dp": 2,
          "days": 12,
          "tone": "pick"
        },
        {
          "cloth": 4,
          "draw": 8,
          "name": "SPORTING TOUCH",
          "filly": false,
          "trainer": "Neelesh Rawal",
          "jockey": "Ajay Kumar",
          "age": "3y b c",
          "wt": 56.0,
          "al": "",
          "bnc": 29,
          "rtgCh": -1,
          "l2": {
            "days": 27,
            "card": "56",
            "pos": 11,
            "odds": "20",
            "btl": 9.0,
            "lto": 11
          },
          "l1": {
            "days": 14,
            "card": "76",
            "pos": 5,
            "odds": "20",
            "btl": 7.0,
            "lto": 56
          },
          "nty": 26.0,
          "open": 30.68,
          "tissue": "25/1",
          "rank": 8,
          "speed": 12.64,
          "track": 60,
          "distDelta": 100,
          "wtDelta": 0.0,
          "cls": "Maiden",
          "hcp": 0.0,
          "dp": 4,
          "days": 14,
          "tone": "plain"
        },
        {
          "cloth": 5,
          "draw": 1,
          "name": "COSTA MESA",
          "filly": true,
          "trainer": "K S V Prasad Raju",
          "jockey": "P Sai Kumar",
          "age": "3y b f",
          "wt": 54.5,
          "al": "",
          "bnc": 28,
          "rtgCh": 1,
          "l2": {
            "days": 12,
            "card": "82",
            "pos": 11,
            "odds": "20",
            "btl": 21.0,
            "lto": -20
          },
          "l1": {
            "days": 5,
            "card": "96",
            "pos": 3,
            "odds": "12",
            "btl": 5.25,
            "lto": 72
          },
          "nty": 9.0,
          "open": 10.62,
          "tissue": "8/1",
          "rank": 4,
          "speed": 12.62,
          "track": 50,
          "distDelta": 100,
          "wtDelta": 0.0,
          "cls": "Maiden",
          "hcp": -1.5,
          "dp": 4,
          "days": 5,
          "tone": "plain"
        },
        {
          "cloth": 6,
          "draw": 6,
          "name": "GACCHANMANASVIN",
          "filly": true,
          "trainer": "Neelesh Rawal",
          "jockey": "Md Ismail",
          "age": "3y b f",
          "wt": 54.5,
          "al": "",
          "bnc": 29,
          "rtgCh": 0,
          "l2": {
            "days": 19,
            "card": "68",
            "pos": 4,
            "odds": "10",
            "btl": 13.0,
            "lto": 40
          },
          "l1": {
            "days": 6,
            "card": "89",
            "pos": 5,
            "odds": "10",
            "btl": 11.0,
            "lto": 40
          },
          "nty": 11.0,
          "open": 12.98,
          "tissue": "10/1",
          "rank": 5,
          "speed": 12.89,
          "track": 70,
          "distDelta": -400,
          "wtDelta": 0.0,
          "cls": "Maiden",
          "hcp": -1.5,
          "dp": 0,
          "days": 6,
          "tone": "plain"
        },
        {
          "cloth": 7,
          "draw": 2,
          "name": "KHAMAGANI",
          "filly": true,
          "trainer": "N Ravinder Singh",
          "jockey": "Gaurav Singh",
          "age": "3y b f",
          "wt": 54.5,
          "al": "",
          "bnc": 28,
          "rtgCh": 0,
          "l2": {
            "days": 27,
            "card": "56",
            "pos": 3,
            "odds": "20",
            "btl": 0.5,
            "lto": 90
          },
          "l1": {
            "days": 12,
            "card": "82",
            "pos": 9,
            "odds": "20",
            "btl": 19.75,
            "lto": -11
          },
          "nty": 13.0,
          "open": 15.34,
          "tissue": "12/1",
          "rank": 6,
          "speed": 13.18,
          "track": 65,
          "distDelta": -200,
          "wtDelta": 0.0,
          "cls": "Maiden",
          "hcp": -1.5,
          "dp": 2,
          "days": 12,
          "tone": "plain"
        },
        {
          "cloth": 8,
          "draw": 5,
          "name": "MY TOUCH",
          "filly": true,
          "trainer": "D Netto",
          "jockey": "Akshay Kumar",
          "age": "3y b f",
          "wt": 54.5,
          "al": "",
          "bnc": null,
          "rtgCh": null,
          "l2": {
            "days": null,
            "card": "",
            "pos": "###",
            "odds": null,
            "btl": null,
            "lto": "###"
          },
          "l1": {
            "days": 5,
            "card": "96",
            "pos": 2,
            "odds": "20",
            "btl": 0.75,
            "lto": 96
          },
          "nty": 3.5,
          "open": 4.13,
          "tissue": "5/2",
          "rank": 1,
          "speed": 12.34,
          "track": 60,
          "distDelta": 100,
          "wtDelta": 0.0,
          "cls": "Maiden",
          "hcp": -1.5,
          "dp": 4,
          "days": 5,
          "tone": "pick"
        }
      ],
      "picks": {
        "win": 8,
        "plc": 3,
        "upset": 1,
        "lto": [
          8,
          3,
          1,
          5
        ],
        "hcpRtg": [
          8,
          1,
          3,
          6
        ],
        "speed": [
          3,
          8,
          1,
          5
        ]
      }
    },
    {
      "no": 2,
      "official": 102,
      "name": "The Falaknuma Trophy Div-2",
      "class": "Class 4 / Handicap Rated 20-45, 3yo+",
      "dist": "1100m",
      "distM": 1100,
      "time": "02:30 PM",
      "timeCode": "2.30",
      "code": "11mC4D2",
      "field": 9,
      "runners": [
        {
          "cloth": 1,
          "draw": 9,
          "name": "COSMIC GIFT",
          "filly": false,
          "trainer": "A Imran Khan",
          "jockey": "P Trevor",
          "age": "3y b c",
          "wt": 60.0,
          "al": "",
          "bnc": 42,
          "rtgCh": 0,
          "l2": {
            "days": 47,
            "card": "20",
            "pos": 2,
            "odds": "6",
            "btl": 11.5,
            "lto": 56
          },
          "l1": {
            "days": 34,
            "card": "42",
            "pos": 6,
            "odds": "20",
            "btl": 5.75,
            "lto": 54
          },
          "nty": 4.0,
          "open": 4.72,
          "tissue": "3/1",
          "rank": 2,
          "speed": 12.59,
          "track": 70,
          "distDelta": -300,
          "wtDelta": 4.0,
          "cls": "Class 4",
          "hcp": 0.0,
          "dp": -2,
          "days": 34,
          "tone": "pick"
        },
        {
          "cloth": 2,
          "draw": 8,
          "name": "VICTORIA DHORA",
          "filly": false,
          "trainer": "M Srinivas Reddy",
          "jockey": "Imran Chisty",
          "age": "3y b g",
          "wt": 58.5,
          "al": "",
          "bnc": 39,
          "rtgCh": 0,
          "l2": {
            "days": 70,
            "card": "142",
            "pos": 6,
            "odds": "20",
            "btl": 15.75,
            "lto": 22
          },
          "l1": {
            "days": 27,
            "card": "54",
            "pos": 4,
            "odds": "4",
            "btl": 13.5,
            "lto": 36
          },
          "nty": 9.0,
          "open": 10.62,
          "tissue": "8/1",
          "rank": 4,
          "speed": 13.25,
          "track": 0,
          "distDelta": -500,
          "wtDelta": -0.5,
          "cls": "Class 4",
          "hcp": -1.5,
          "dp": -4,
          "days": 27,
          "tone": "plain"
        },
        {
          "cloth": 3,
          "draw": 7,
          "name": "MY WAY MY RULES",
          "filly": false,
          "trainer": "Magan Singh",
          "jockey": "Vivek G",
          "age": "3y b c",
          "wt": 58.0,
          "al": "",
          "bnc": 38,
          "rtgCh": 0,
          "l2": {
            "days": 54,
            "card": "3",
            "pos": 1,
            "odds": "9",
            "btl": 0.0,
            "lto": 114
          },
          "l1": {
            "days": 34,
            "card": "42",
            "pos": 9,
            "odds": "20",
            "btl": 17.0,
            "lto": -2
          },
          "nty": 5.0,
          "open": 5.9,
          "tissue": "4/1",
          "rank": 3,
          "speed": 13.12,
          "track": 65,
          "distDelta": -300,
          "wtDelta": 2.0,
          "cls": "Class 4",
          "hcp": -2.0,
          "dp": -2,
          "days": 34,
          "tone": "pick"
        },
        {
          "cloth": 4,
          "draw": 2,
          "name": "MATERIALITY",
          "filly": true,
          "trainer": "L V R Deshmukh",
          "jockey": "P Ajeeth Kumar",
          "age": "3y b f",
          "wt": 57.0,
          "al": "",
          "bnc": 36,
          "rtgCh": null,
          "l2": {
            "days": null,
            "card": "",
            "pos": "###",
            "odds": null,
            "btl": null,
            "lto": "###"
          },
          "l1": {
            "days": 41,
            "card": "24",
            "pos": 1,
            "odds": "5.5",
            "btl": 0.0,
            "lto": 120
          },
          "nty": 3.5,
          "open": 4.13,
          "tissue": "5/2",
          "rank": 1,
          "speed": 12.28,
          "track": 70,
          "distDelta": 0,
          "wtDelta": 2.5,
          "cls": "Class 4",
          "hcp": -3.0,
          "dp": -2,
          "days": 41,
          "tone": "pick"
        },
        {
          "cloth": 5,
          "draw": 6,
          "name": "BEVERLEY",
          "filly": true,
          "trainer": "Ananta Vatsalya",
          "jockey": "Arjun",
          "age": "4y b f",
          "wt": 55.5,
          "al": "",
          "bnc": 33,
          "rtgCh": -2,
          "l2": {
            "days": 47,
            "card": "17",
            "pos": 7,
            "odds": "6",
            "btl": 10.5,
            "lto": 27
          },
          "l1": {
            "days": 14,
            "card": "78",
            "pos": 14,
            "odds": "20",
            "btl": 37.0,
            "lto": "###"
          },
          "nty": 21.0,
          "open": 24.78,
          "tissue": "20/1",
          "rank": 7,
          "speed": 14.05,
          "track": 65,
          "distDelta": -300,
          "wtDelta": -1.0,
          "cls": "Class 4",
          "hcp": -4.5,
          "dp": 2,
          "days": 14,
          "tone": "plain"
        },
        {
          "cloth": 6,
          "draw": 3,
          "name": "CELESTIAL POWER",
          "filly": false,
          "trainer": "Raza Shehzad",
          "jockey": "P Uday Kiran",
          "age": "4y b g",
          "wt": 54.0,
          "al": "",
          "bnc": 30,
          "rtgCh": 0,
          "l2": {
            "days": null,
            "card": "",
            "pos": "###",
            "odds": null,
            "btl": null,
            "lto": "###"
          },
          "l1": {
            "days": 47,
            "card": "17",
            "pos": 11,
            "odds": "20",
            "btl": 45.25,
            "lto": "###"
          },
          "nty": 34.0,
          "open": 40.12,
          "tissue": "33/1",
          "rank": 9,
          "speed": 15.04,
          "track": 50,
          "distDelta": -100,
          "wtDelta": -0.5,
          "cls": "Class 4",
          "hcp": -6.0,
          "dp": -2,
          "days": 47,
          "tone": "plain"
        },
        {
          "cloth": 7,
          "draw": 5,
          "name": "ANEMOI",
          "filly": false,
          "trainer": "M F Ali Khan",
          "jockey": "Surya Prakash",
          "age": "5y b g",
          "wt": 53.0,
          "al": "",
          "bnc": 28,
          "rtgCh": -2,
          "l2": {
            "days": 33,
            "card": "47",
            "pos": 5,
            "odds": "20",
            "btl": 9.25,
            "lto": 49
          },
          "l1": {
            "days": 14,
            "card": "78",
            "pos": 10,
            "odds": "20",
            "btl": 30.75,
            "lto": "###"
          },
          "nty": 13.0,
          "open": 15.34,
          "tissue": "12/1",
          "rank": 5,
          "speed": 13.76,
          "track": 0,
          "distDelta": -300,
          "wtDelta": -1.0,
          "cls": "Class 4",
          "hcp": -7.0,
          "dp": 2,
          "days": 14,
          "tone": "plain"
        },
        {
          "cloth": 8,
          "draw": 4,
          "name": "BARBAROSSA",
          "filly": true,
          "trainer": "K S V Prasad Raju",
          "jockey": "Ajay Kumar",
          "age": "4y ch f",
          "wt": 52.5,
          "al": "",
          "bnc": 27,
          "rtgCh": null,
          "l2": {
            "days": null,
            "card": "",
            "pos": "###",
            "odds": null,
            "btl": null,
            "lto": "###"
          },
          "l1": {
            "days": null,
            "card": "",
            "pos": "###",
            "odds": null,
            "btl": null,
            "lto": "###"
          },
          "nty": 17.0,
          "open": 20.06,
          "tissue": "16/1",
          "rank": 6,
          "speed": null,
          "track": 45,
          "distDelta": null,
          "wtDelta": null,
          "cls": "Class 4",
          "hcp": -7.5,
          "dp": null,
          "days": null,
          "tone": "plain"
        },
        {
          "cloth": 9,
          "draw": 1,
          "name": "TIMELESS ELEGANCE",
          "filly": true,
          "trainer": "Robin R Kondakalla",
          "jockey": "G Naresh",
          "age": "4y b f",
          "wt": 51.0,
          "al": "",
          "bnc": 24,
          "rtgCh": 0,
          "l2": {
            "days": 47,
            "card": "22",
            "pos": 6,
            "odds": "20",
            "btl": 11.0,
            "lto": 37
          },
          "l1": {
            "days": 20,
            "card": "63",
            "pos": 5,
            "odds": "15",
            "btl": 21.0,
            "lto": 10
          },
          "nty": 21.0,
          "open": 24.78,
          "tissue": "20/1",
          "rank": 8,
          "speed": 13.52,
          "track": 65,
          "distDelta": 0,
          "wtDelta": -6.0,
          "cls": "Class 4",
          "hcp": -9.0,
          "dp": 2,
          "days": 20,
          "tone": "plain"
        }
      ],
      "picks": {
        "win": 4,
        "plc": 1,
        "upset": 3,
        "lto": [
          4,
          1,
          2,
          9
        ],
        "hcpRtg": [
          1,
          2,
          3,
          4
        ],
        "speed": [
          4,
          1,
          3,
          2
        ]
      }
    },
    {
      "no": 3,
      "official": 103,
      "name": "The Falaknuma Trophy Div-1",
      "class": "Class 4 / Handicap Rated 20-45, 3yo+",
      "dist": "1100m",
      "distM": 1100,
      "time": "03:05 PM",
      "timeCode": "3.05",
      "code": "11mC4D1",
      "field": 10,
      "runners": [
        {
          "cloth": 1,
          "draw": 3,
          "name": "COMING HOME",
          "filly": true,
          "trainer": "Magan Singh",
          "jockey": "B Nikhil",
          "age": "8y dkb m",
          "wt": 60.5,
          "al": "",
          "bnc": 43,
          "rtgCh": -2,
          "l2": {
            "days": 20,
            "card": "66",
            "pos": 9,
            "odds": "20",
            "btl": 18.25,
            "lto": -6
          },
          "l1": {
            "days": 6,
            "card": "94",
            "pos": 5,
            "odds": "20",
            "btl": 15.5,
            "lto": 29
          },
          "nty": 21.0,
          "open": 24.78,
          "tissue": "20/1",
          "rank": 7,
          "speed": 13.27,
          "track": 55,
          "distDelta": -300,
          "wtDelta": 0.5,
          "cls": "Class 4",
          "hcp": 0.0,
          "dp": 2,
          "days": 6,
          "tone": "plain"
        },
        {
          "cloth": 2,
          "draw": 2,
          "name": "SHE'S A BOMB",
          "filly": true,
          "trainer": "D Netto",
          "jockey": "Surendra Singh",
          "age": "3y b f",
          "wt": 60.0,
          "al": "-5",
          "bnc": 42,
          "rtgCh": 15,
          "l2": {
            "days": 40,
            "card": "32",
            "pos": 5,
            "odds": "15",
            "btl": 13.0,
            "lto": 35
          },
          "l1": {
            "days": 19,
            "card": "68",
            "pos": 1,
            "odds": "8",
            "btl": 0.0,
            "lto": 114
          },
          "nty": 3.0,
          "open": 3.54,
          "tissue": "2/1",
          "rank": 1,
          "speed": 12.28,
          "track": 65,
          "distDelta": -100,
          "wtDelta": 5.5,
          "cls": "Class 4",
          "hcp": -5.5,
          "dp": 2,
          "days": 19,
          "tone": "pick"
        },
        {
          "cloth": 3,
          "draw": 1,
          "name": "AMERICAN AFFAIR",
          "filly": true,
          "trainer": "Ananta Vatsalya",
          "jockey": "A Ashhad Asbar",
          "age": "4y b f",
          "wt": 57.5,
          "al": "",
          "bnc": 37,
          "rtgCh": 3,
          "l2": {
            "days": 47,
            "card": "23",
            "pos": 2,
            "odds": "5",
            "btl": 2.75,
            "lto": 84
          },
          "l1": {
            "days": 41,
            "card": "30",
            "pos": 2,
            "odds": "2.5",
            "btl": 1.5,
            "lto": 87
          },
          "nty": 4.0,
          "open": 4.72,
          "tissue": "3/1",
          "rank": 2,
          "speed": 12.54,
          "track": 99,
          "distDelta": -100,
          "wtDelta": 1.5,
          "cls": "Class 4",
          "hcp": -3.0,
          "dp": -2,
          "days": 41,
          "tone": "pick"
        },
        {
          "cloth": 4,
          "draw": 4,
          "name": "LA QUINTA",
          "filly": false,
          "trainer": "K S V Prasad Raju",
          "jockey": "Akshay Kumar",
          "age": "4y b g",
          "wt": 57.5,
          "al": "",
          "bnc": 37,
          "rtgCh": 0,
          "l2": {
            "days": 40,
            "card": "33",
            "pos": 4,
            "odds": "10",
            "btl": 5.0,
            "lto": 66
          },
          "l1": {
            "days": 27,
            "card": "59",
            "pos": 12,
            "odds": "12",
            "btl": 40.75,
            "lto": "###"
          },
          "nty": 6.0,
          "open": 7.08,
          "tissue": "5/1",
          "rank": 3,
          "speed": null,
          "track": 50,
          "distDelta": -300,
          "wtDelta": -2.5,
          "cls": "Class 4",
          "hcp": -3.0,
          "dp": -2,
          "days": 27,
          "tone": "pick"
        },
        {
          "cloth": 5,
          "draw": 8,
          "name": "FLARE",
          "filly": true,
          "trainer": "Ananta Vatsalya",
          "jockey": "V S Shekhawat",
          "age": "5y b m",
          "wt": 55.0,
          "al": "-5",
          "bnc": 32,
          "rtgCh": 0,
          "l2": {
            "days": 41,
            "card": "29",
            "pos": 6,
            "odds": "2.5",
            "btl": 15.25,
            "lto": 17
          },
          "l1": {
            "days": 34,
            "card": "43",
            "pos": 10,
            "odds": "12",
            "btl": 33.0,
            "lto": "###"
          },
          "nty": 9.0,
          "open": 10.62,
          "tissue": "8/1",
          "rank": 4,
          "speed": 14.03,
          "track": 0,
          "distDelta": -500,
          "wtDelta": 0.5,
          "cls": "Class 4",
          "hcp": -10.5,
          "dp": -4,
          "days": 34,
          "tone": "plain"
        },
        {
          "cloth": 6,
          "draw": 10,
          "name": "LEGO",
          "filly": true,
          "trainer": "G Sandeep",
          "jockey": "Kuldeep Singh",
          "age": "5y b m",
          "wt": 54.5,
          "al": "",
          "bnc": 31,
          "rtgCh": -3,
          "l2": {
            "days": 20,
            "card": "60",
            "pos": 5,
            "odds": "40",
            "btl": 24.25,
            "lto": 6
          },
          "l1": {
            "days": 14,
            "card": "78",
            "pos": 9,
            "odds": "20",
            "btl": 26.0,
            "lto": "###"
          },
          "nty": 21.0,
          "open": 24.78,
          "tissue": "20/1",
          "rank": 8,
          "speed": 13.53,
          "track": 60,
          "distDelta": -300,
          "wtDelta": -1.5,
          "cls": "Class 4",
          "hcp": -6.0,
          "dp": 2,
          "days": 14,
          "tone": "plain"
        },
        {
          "cloth": 7,
          "draw": 7,
          "name": "COMMANDING WARRIOR",
          "filly": false,
          "trainer": "Raza Shehzad",
          "jockey": "Surya Prakash",
          "age": "4y b g",
          "wt": 53.0,
          "al": "",
          "bnc": 28,
          "rtgCh": null,
          "l2": {
            "days": null,
            "card": "",
            "pos": "###",
            "odds": null,
            "btl": null,
            "lto": "###"
          },
          "l1": {
            "days": 354,
            "card": "121",
            "pos": 6,
            "odds": "20",
            "btl": 14.25,
            "lto": 26
          },
          "nty": 26.0,
          "open": 30.68,
          "tissue": "25/1",
          "rank": 9,
          "speed": 12.92,
          "track": 0,
          "distDelta": -300,
          "wtDelta": -3.0,
          "cls": "Class 4",
          "hcp": -7.5,
          "dp": -10,
          "days": 354,
          "tone": "risk"
        },
        {
          "cloth": 8,
          "draw": 9,
          "name": "GOLDEN AURA",
          "filly": false,
          "trainer": "M Srinivas Reddy",
          "jockey": "G Naresh",
          "age": "4y ch g",
          "wt": 52.0,
          "al": "",
          "bnc": 26,
          "rtgCh": 0,
          "l2": {
            "days": 53,
            "card": "9",
            "pos": 6,
            "odds": "10",
            "btl": 18.75,
            "lto": 9
          },
          "l1": {
            "days": 14,
            "card": "81",
            "pos": 4,
            "odds": "20",
            "btl": 14.5,
            "lto": 39
          },
          "nty": 13.0,
          "open": 15.34,
          "tissue": "12/1",
          "rank": 5,
          "speed": 13.22,
          "track": 0,
          "distDelta": -100,
          "wtDelta": -5.0,
          "cls": "Class 4",
          "hcp": -8.5,
          "dp": 4,
          "days": 14,
          "tone": "plain"
        },
        {
          "cloth": 9,
          "draw": 5,
          "name": "SANTORINI SKY",
          "filly": true,
          "trainer": "Magan Singh",
          "jockey": "D S Deora",
          "age": "4y b f",
          "wt": 51.5,
          "al": "",
          "bnc": 25,
          "rtgCh": -2,
          "l2": {
            "days": null,
            "card": "",
            "pos": "###",
            "odds": null,
            "btl": null,
            "lto": "###"
          },
          "l1": {
            "days": 349,
            "card": "131",
            "pos": 15,
            "odds": "20",
            "btl": 38.5,
            "lto": "###"
          },
          "nty": 34.0,
          "open": 40.12,
          "tissue": "33/1",
          "rank": 10,
          "speed": null,
          "track": 60,
          "distDelta": -100,
          "wtDelta": 0.5,
          "cls": "Class 4",
          "hcp": -9.0,
          "dp": -8,
          "days": 349,
          "tone": "risk"
        },
        {
          "cloth": 10,
          "draw": 6,
          "name": "RATE OF INTEREST",
          "filly": true,
          "trainer": "Robin R Kondakalla",
          "jockey": "Arjun",
          "age": "4y ch f",
          "wt": 50.0,
          "al": "",
          "bnc": 22,
          "rtgCh": 0,
          "l2": {
            "days": 33,
            "card": "47",
            "pos": 8,
            "odds": "20",
            "btl": 11.75,
            "lto": 21
          },
          "l1": {
            "days": 20,
            "card": "63",
            "pos": 8,
            "odds": "20",
            "btl": 25.0,
            "lto": "###"
          },
          "nty": 26.0,
          "open": 30.68,
          "tissue": "25/1",
          "rank": 6,
          "speed": 13.77,
          "track": 0,
          "distDelta": 0,
          "wtDelta": -6.0,
          "cls": "Class 4",
          "hcp": -10.5,
          "dp": 2,
          "days": 20,
          "tone": "plain"
        }
      ],
      "picks": {
        "win": 2,
        "plc": 3,
        "upset": 4,
        "lto": [
          2,
          3,
          8,
          1
        ],
        "hcpRtg": [
          1,
          2,
          3,
          4
        ],
        "speed": [
          2,
          3,
          7,
          8
        ]
      }
    },
    {
      "no": 4,
      "official": 104,
      "name": "The Totaram's Cup",
      "class": "For Horses / 3 Year Olds and Upward",
      "dist": "1200m",
      "distM": 1200,
      "time": "03:40 PM",
      "timeCode": "3.40",
      "code": "12mTRM",
      "field": 9,
      "runners": [
        {
          "cloth": 1,
          "draw": 7,
          "name": "CELESTIAL",
          "filly": false,
          "trainer": "Laxman Singh",
          "jockey": "Gaurav Singh",
          "age": "5y b g",
          "wt": 58.0,
          "al": "",
          "bnc": 81,
          "rtgCh": 0,
          "l2": {
            "days": 47,
            "card": "21",
            "pos": 6,
            "odds": "7",
            "btl": 9.75,
            "lto": 36
          },
          "l1": {
            "days": 20,
            "card": "62",
            "pos": 8,
            "odds": "20",
            "btl": 8.25,
            "lto": 33
          },
          "nty": 13.0,
          "open": 15.34,
          "tissue": "12/1",
          "rank": 6,
          "speed": 12.5,
          "track": 99,
          "distDelta": -200,
          "wtDelta": 8.0,
          "cls": "Terms",
          "hcp": 0.0,
          "dp": 0,
          "days": 20,
          "tone": "plain"
        },
        {
          "cloth": 2,
          "draw": 9,
          "name": "ONE N ONLY",
          "filly": false,
          "trainer": "D Netto",
          "jockey": "Akshay Kumar",
          "age": "5y b g",
          "wt": 54.5,
          "al": "",
          "bnc": 107,
          "rtgCh": 8,
          "l2": {
            "days": 54,
            "card": "7",
            "pos": 5,
            "odds": "4",
            "btl": 2.5,
            "lto": 65
          },
          "l1": {
            "days": 27,
            "card": "57",
            "pos": 1,
            "odds": "2.75",
            "btl": 0.0,
            "lto": 127
          },
          "nty": 3.25,
          "open": 3.83,
          "tissue": "9/4",
          "rank": 1,
          "speed": 12.29,
          "track": 70,
          "distDelta": 0,
          "wtDelta": -5.5,
          "cls": "Terms",
          "hcp": -3.5,
          "dp": 0,
          "days": 27,
          "tone": "pick"
        },
        {
          "cloth": 3,
          "draw": 6,
          "name": "SHADOW OF THE MOON",
          "filly": false,
          "trainer": "A Imran Khan",
          "jockey": "S Saqlain",
          "age": "6y gr h",
          "wt": 53.5,
          "al": "",
          "bnc": 70,
          "rtgCh": -3,
          "l2": {
            "days": 19,
            "card": "73",
            "pos": 8,
            "odds": "20",
            "btl": 25.75,
            "lto": "###"
          },
          "l1": {
            "days": 12,
            "card": "83",
            "pos": 8,
            "odds": "20",
            "btl": 18.75,
            "lto": -1
          },
          "nty": 34.0,
          "open": 40.12,
          "tissue": "33/1",
          "rank": 9,
          "speed": 13.0,
          "track": 65,
          "distDelta": -600,
          "wtDelta": 0.0,
          "cls": "Terms",
          "hcp": -4.5,
          "dp": 0,
          "days": 12,
          "tone": "plain"
        },
        {
          "cloth": 4,
          "draw": 8,
          "name": "UCHCHAIHSHRAVAS",
          "filly": false,
          "trainer": "Neelesh Rawal",
          "jockey": "Neeraj Rawal",
          "age": "5y b h",
          "wt": 53.5,
          "al": "",
          "bnc": 90,
          "rtgCh": 0,
          "l2": {
            "days": 33,
            "card": "50",
            "pos": 5,
            "odds": "20",
            "btl": 3.0,
            "lto": 69
          },
          "l1": {
            "days": 20,
            "card": "62",
            "pos": 5,
            "odds": "5.5",
            "btl": 3.5,
            "lto": 62
          },
          "nty": 9.0,
          "open": 10.62,
          "tissue": "8/1",
          "rank": 5,
          "speed": 12.28,
          "track": 45,
          "distDelta": -200,
          "wtDelta": 3.5,
          "cls": "Terms",
          "hcp": -4.5,
          "dp": 0,
          "days": 20,
          "tone": "plain"
        },
        {
          "cloth": 5,
          "draw": 2,
          "name": "BLACK ONYX",
          "filly": false,
          "trainer": "Magan Singh",
          "jockey": "D S Deora",
          "age": "8y dkb g",
          "wt": 52.0,
          "al": "",
          "bnc": 100,
          "rtgCh": 3,
          "l2": {
            "days": 33,
            "card": "50",
            "pos": 2,
            "odds": "8",
            "btl": 2.0,
            "lto": 87
          },
          "l1": {
            "days": 6,
            "card": "93",
            "pos": 2,
            "odds": "12",
            "btl": 2.75,
            "lto": 86
          },
          "nty": 5.0,
          "open": 5.9,
          "tissue": "4/1",
          "rank": 3,
          "speed": 12.39,
          "track": 99,
          "distDelta": -200,
          "wtDelta": -6.5,
          "cls": "Terms",
          "hcp": -6.0,
          "dp": 2,
          "days": 6,
          "tone": "pick"
        },
        {
          "cloth": 6,
          "draw": 1,
          "name": "DETECTIVE",
          "filly": false,
          "trainer": "N Ravinder Singh",
          "jockey": "Vikram Singh",
          "age": "6y b h",
          "wt": 52.0,
          "al": "",
          "bnc": 67,
          "rtgCh": -2,
          "l2": {
            "days": 41,
            "card": "28",
            "pos": 7,
            "odds": "15",
            "btl": 25.25,
            "lto": "###"
          },
          "l1": {
            "days": 12,
            "card": "84",
            "pos": 9,
            "odds": "20",
            "btl": 9.5,
            "lto": 22
          },
          "nty": 26.0,
          "open": 30.68,
          "tissue": "25/1",
          "rank": 8,
          "speed": 12.84,
          "track": 80,
          "distDelta": 0,
          "wtDelta": -2.0,
          "cls": "Terms",
          "hcp": -6.0,
          "dp": 4,
          "days": 12,
          "tone": "plain"
        },
        {
          "cloth": 7,
          "draw": 3,
          "name": "CALISTA GIRL",
          "filly": true,
          "trainer": "N Ravinder Singh",
          "jockey": "Bhawani Singh",
          "age": "6y ch m",
          "wt": 50.5,
          "al": "",
          "bnc": 69,
          "rtgCh": -2,
          "l2": {
            "days": 27,
            "card": "52",
            "pos": 8,
            "odds": "20",
            "btl": 16.75,
            "lto": 5
          },
          "l1": {
            "days": 12,
            "card": "87",
            "pos": 10,
            "odds": "20",
            "btl": 16.5,
            "lto": -7
          },
          "nty": 21.0,
          "open": 24.78,
          "tissue": "20/1",
          "rank": 7,
          "speed": 13.12,
          "track": 65,
          "distDelta": 0,
          "wtDelta": -5.0,
          "cls": "Terms",
          "hcp": -7.5,
          "dp": 4,
          "days": 12,
          "tone": "plain"
        },
        {
          "cloth": 8,
          "draw": 4,
          "name": "EMERALD TOUCH",
          "filly": true,
          "trainer": "Neelesh Rawal",
          "jockey": "M S Deora",
          "age": "4y b f",
          "wt": 50.5,
          "al": "",
          "bnc": 69,
          "rtgCh": 9,
          "l2": {
            "days": 54,
            "card": "6",
            "pos": 2,
            "odds": "9",
            "btl": 0.0,
            "lto": 94
          },
          "l1": {
            "days": 33,
            "card": "48",
            "pos": 1,
            "odds": "1.6",
            "btl": 0.0,
            "lto": 130
          },
          "nty": 4.0,
          "open": 4.72,
          "tissue": "3/1",
          "rank": 2,
          "speed": 12.3,
          "track": 65,
          "distDelta": 0,
          "wtDelta": -8.0,
          "cls": "Terms",
          "hcp": -7.5,
          "dp": 0,
          "days": 33,
          "tone": "pick"
        },
        {
          "cloth": 9,
          "draw": 5,
          "name": "REIGNING BEAUTY",
          "filly": true,
          "trainer": "Neelesh Rawal",
          "jockey": "Santosh Raj N R",
          "age": "6y gr m",
          "wt": 50.5,
          "al": "",
          "bnc": 90,
          "rtgCh": 3,
          "l2": {
            "days": 33,
            "card": "50",
            "pos": 7,
            "odds": "20",
            "btl": 3.5,
            "lto": 54
          },
          "l1": {
            "days": 6,
            "card": "93",
            "pos": 2,
            "odds": "5.5",
            "btl": 2.75,
            "lto": 84
          },
          "nty": 7.0,
          "open": 8.26,
          "tissue": "6/1",
          "rank": 4,
          "speed": 12.32,
          "track": 55,
          "distDelta": -200,
          "wtDelta": -3.0,
          "cls": "Terms",
          "hcp": -7.5,
          "dp": 2,
          "days": 6,
          "tone": "plain"
        }
      ],
      "picks": {
        "win": 2,
        "plc": 8,
        "upset": 5,
        "lto": [
          8,
          2,
          5,
          9
        ],
        "hcpRtg": [
          2,
          5,
          9,
          4
        ],
        "speed": [
          4,
          2,
          8,
          9
        ]
      }
    },
    {
      "no": 5,
      "official": 105,
      "name": "The President Of India Gold Cup (Gr.2)",
      "class": "Terms / 4 Year Olds and Upward",
      "dist": "2400m",
      "distM": 2400,
      "time": "04:15 PM",
      "timeCode": "4.15",
      "code": "24mG2",
      "field": 7,
      "runners": [
        {
          "cloth": 1,
          "draw": 7,
          "name": "DUKE OF TUSCANY",
          "filly": false,
          "trainer": "P Shroff",
          "jockey": "R Ajinkya",
          "age": "5y b g",
          "wt": 60.0,
          "al": "",
          "bnc": 120,
          "rtgCh": 0,
          "l2": {
            "days": 50,
            "card": "194",
            "pos": 2,
            "odds": "3.5",
            "btl": 1.0,
            "lto": 89
          },
          "l1": {
            "days": 21,
            "card": "63",
            "pos": 1,
            "odds": "15",
            "btl": 0.0,
            "lto": 114
          },
          "nty": 3.5,
          "open": 4.13,
          "tissue": "5/2",
          "rank": 2,
          "speed": 12.45,
          "track": 90,
          "distDelta": 0,
          "wtDelta": 0.0,
          "cls": "Gr.2",
          "hcp": 0.0,
          "dp": 2,
          "days": 21,
          "tone": "pick"
        },
        {
          "cloth": 2,
          "draw": 1,
          "name": "RAMIEL",
          "filly": false,
          "trainer": "Bharath Singh",
          "jockey": "Antony Raj S",
          "age": "6y ch g",
          "wt": 58.0,
          "al": "",
          "bnc": 121,
          "rtgCh": 11,
          "l2": {
            "days": 76,
            "card": "133",
            "pos": 9,
            "odds": "20",
            "btl": 15.5,
            "lto": 3
          },
          "l1": {
            "days": 50,
            "card": "194",
            "pos": 1,
            "odds": "12",
            "btl": 0.0,
            "lto": 114
          },
          "nty": 7.0,
          "open": 8.26,
          "tissue": "6/1",
          "rank": 4,
          "speed": 12.73,
          "track": 99,
          "distDelta": -400,
          "wtDelta": -0.5,
          "cls": "Gr.2",
          "hcp": -2.0,
          "dp": -6,
          "days": 50,
          "tone": "plain"
        },
        {
          "cloth": 3,
          "draw": 5,
          "name": "DYF",
          "filly": false,
          "trainer": "Adhiraj S Jodha",
          "jockey": "Yash Narredu",
          "age": "7y gr h",
          "wt": 57.0,
          "al": "",
          "bnc": 114,
          "rtgCh": 0,
          "l2": {
            "days": 180,
            "card": "33",
            "pos": 1,
            "odds": "2.8",
            "btl": 0.0,
            "lto": 127
          },
          "l1": {
            "days": 50,
            "card": "194",
            "pos": 3,
            "odds": "3.25",
            "btl": 2.25,
            "lto": 78
          },
          "nty": 5.0,
          "open": 5.9,
          "tissue": "4/1",
          "rank": 3,
          "speed": 12.78,
          "track": 99,
          "distDelta": -400,
          "wtDelta": -1.5,
          "cls": "Gr.2",
          "hcp": -3.0,
          "dp": -6,
          "days": 50,
          "tone": "pick"
        },
        {
          "cloth": 4,
          "draw": 6,
          "name": "ZUCCARO",
          "filly": false,
          "trainer": "P Shroff",
          "jockey": "Vivek G",
          "age": "6y ch g",
          "wt": 56.5,
          "al": "",
          "bnc": 123,
          "rtgCh": 6,
          "l2": {
            "days": 104,
            "card": "78",
            "pos": 1,
            "odds": "1.6",
            "btl": 0.0,
            "lto": 130
          },
          "l1": {
            "days": 76,
            "card": "133",
            "pos": 1,
            "odds": "1.85",
            "btl": 0.0,
            "lto": 129
          },
          "nty": 2.75,
          "open": 3.24,
          "tissue": "7/4",
          "rank": 1,
          "speed": 12.16,
          "track": 99,
          "distDelta": 200,
          "wtDelta": -0.5,
          "cls": "Gr.2",
          "hcp": -3.5,
          "dp": -10,
          "days": 76,
          "tone": "pick"
        },
        {
          "cloth": 5,
          "draw": 3,
          "name": "MIRACLE STAR",
          "filly": true,
          "trainer": "James Mckeown",
          "jockey": "P Trevor",
          "age": "4y b f",
          "wt": 55.5,
          "al": "",
          "bnc": 109,
          "rtgCh": 0,
          "l2": {
            "days": 91,
            "card": "99",
            "pos": 3,
            "odds": "3",
            "btl": 3.75,
            "lto": 73
          },
          "l1": {
            "days": 76,
            "card": "133",
            "pos": 5,
            "odds": "8",
            "btl": 9.25,
            "lto": 44
          },
          "nty": 9.0,
          "open": 10.62,
          "tissue": "8/1",
          "rank": 5,
          "speed": 12.41,
          "track": 80,
          "distDelta": 200,
          "wtDelta": -0.5,
          "cls": "Gr.2",
          "hcp": -4.5,
          "dp": -10,
          "days": 76,
          "tone": "plain"
        },
        {
          "cloth": 6,
          "draw": 4,
          "name": "HIGH COMMAND",
          "filly": false,
          "trainer": "L V R Deshmukh",
          "jockey": "P Ajeeth Kumar",
          "age": "6y b h",
          "wt": 53.0,
          "al": "",
          "bnc": 99,
          "rtgCh": 0,
          "l2": {
            "days": 224,
            "card": "128",
            "pos": 4,
            "odds": "20",
            "btl": 10.25,
            "lto": 52
          },
          "l1": {
            "days": 33,
            "card": "50",
            "pos": 10,
            "odds": "12",
            "btl": 11.5,
            "lto": 6
          },
          "nty": 26.0,
          "open": 30.68,
          "tissue": "25/1",
          "rank": 7,
          "speed": 12.8,
          "track": 70,
          "distDelta": 1000,
          "wtDelta": -6.0,
          "cls": "Gr.2",
          "hcp": -7.0,
          "dp": -4,
          "days": 33,
          "tone": "plain"
        },
        {
          "cloth": 7,
          "draw": 2,
          "name": "VYASA",
          "filly": false,
          "trainer": "G Sandeep",
          "jockey": "A Ashhad Asbar",
          "age": "6y ch g",
          "wt": 52.0,
          "al": "",
          "bnc": 90,
          "rtgCh": 8,
          "l2": {
            "days": 186,
            "card": "24",
            "pos": 1,
            "odds": "1.9",
            "btl": 0.0,
            "lto": 129
          },
          "l1": {
            "days": 33,
            "card": "49",
            "pos": 2,
            "odds": "15",
            "btl": 0.75,
            "lto": 94
          },
          "nty": 21.0,
          "open": 24.78,
          "tissue": "20/1",
          "rank": 6,
          "speed": 12.37,
          "track": 75,
          "distDelta": 400,
          "wtDelta": -1.5,
          "cls": "Gr.2",
          "hcp": -8.0,
          "dp": -4,
          "days": 33,
          "tone": "plain"
        }
      ],
      "picks": {
        "win": 4,
        "plc": 1,
        "upset": 3,
        "lto": [
          4,
          1,
          2,
          7
        ],
        "hcpRtg": [
          4,
          2,
          1,
          3
        ],
        "speed": [
          4,
          7,
          5,
          1
        ]
      }
    },
    {
      "no": 6,
      "official": 106,
      "name": "The Nelston Plate",
      "class": "Class 4 / Handicap Rated 20-45, 4yo+",
      "dist": "1600m",
      "distM": 1600,
      "time": "04:50 PM",
      "timeCode": "4.50",
      "code": "16mC4",
      "field": 10,
      "runners": [
        {
          "cloth": 1,
          "draw": 2,
          "name": "ONSLAUGHT",
          "filly": false,
          "trainer": "Raza Shehzad",
          "jockey": "Imran Chisty",
          "age": "4y b g",
          "wt": 61.0,
          "al": "",
          "bnc": 43,
          "rtgCh": 1,
          "l2": {
            "days": 172,
            "card": "52",
            "pos": 6,
            "odds": "5",
            "btl": 18.0,
            "lto": 9
          },
          "l1": {
            "days": 34,
            "card": "41",
            "pos": 3,
            "odds": "9",
            "btl": 6.75,
            "lto": 66
          },
          "nty": 4.0,
          "open": 4.72,
          "tissue": "3/1",
          "rank": 2,
          "speed": 12.72,
          "track": 65,
          "distDelta": 200,
          "wtDelta": 1.0,
          "cls": "Class 4",
          "hcp": 0.0,
          "dp": -2,
          "days": 34,
          "tone": "pick"
        },
        {
          "cloth": 2,
          "draw": 8,
          "name": "HOPING HIGH",
          "filly": false,
          "trainer": "Jasbir Singh",
          "jockey": "Mohit Singh",
          "age": "5y b h",
          "wt": 58.5,
          "al": "",
          "bnc": 38,
          "rtgCh": 9,
          "l2": {
            "days": 19,
            "card": "70",
            "pos": 6,
            "odds": "10",
            "btl": 10.5,
            "lto": 35
          },
          "l1": {
            "days": 12,
            "card": "85",
            "pos": 1,
            "odds": "6",
            "btl": 0.0,
            "lto": 119
          },
          "nty": 6.0,
          "open": 7.08,
          "tissue": "5/1",
          "rank": 4,
          "speed": 12.86,
          "track": 70,
          "distDelta": 0,
          "wtDelta": 5.0,
          "cls": "Class 4",
          "hcp": -2.5,
          "dp": 4,
          "days": 12,
          "tone": "plain"
        },
        {
          "cloth": 3,
          "draw": 9,
          "name": "SILVER ARROW",
          "filly": true,
          "trainer": "A Imran Khan",
          "jockey": "A A Vikrant",
          "age": "7y gr m",
          "wt": 58.5,
          "al": "",
          "bnc": 38,
          "rtgCh": 0,
          "l2": {
            "days": 34,
            "card": "43",
            "pos": 5,
            "odds": "12",
            "btl": 13.0,
            "lto": 34
          },
          "l1": {
            "days": 12,
            "card": "85",
            "pos": 6,
            "odds": "15",
            "btl": 8.75,
            "lto": 42
          },
          "nty": 11.0,
          "open": 12.98,
          "tissue": "10/1",
          "rank": 6,
          "speed": 13.22,
          "track": 50,
          "distDelta": 0,
          "wtDelta": 0.5,
          "cls": "Class 4",
          "hcp": -2.5,
          "dp": 4,
          "days": 12,
          "tone": "plain"
        },
        {
          "cloth": 4,
          "draw": 1,
          "name": "QUINTESSENTIAL",
          "filly": true,
          "trainer": "L V R Deshmukh",
          "jockey": "P Ajeeth Kumar",
          "age": "4y b f",
          "wt": 57.0,
          "al": "",
          "bnc": 35,
          "rtgCh": 1,
          "l2": {
            "days": 41,
            "card": "27",
            "pos": 1,
            "odds": "3.25",
            "btl": 0.0,
            "lto": 126
          },
          "l1": {
            "days": 27,
            "card": "54",
            "pos": 3,
            "odds": "3.5",
            "btl": 4.25,
            "lto": 72
          },
          "nty": 3.5,
          "open": 4.13,
          "tissue": "5/2",
          "rank": 1,
          "speed": 12.88,
          "track": 70,
          "distDelta": 0,
          "wtDelta": 0.5,
          "cls": "Class 4",
          "hcp": -4.0,
          "dp": 0,
          "days": 27,
          "tone": "pick"
        },
        {
          "cloth": 5,
          "draw": 10,
          "name": "PHOTOGRAPH",
          "filly": false,
          "trainer": "Robin R Kondakalla",
          "jockey": "G Naresh",
          "age": "4y gr g",
          "wt": 55.0,
          "al": "",
          "bnc": 31,
          "rtgCh": -2,
          "l2": {
            "days": 34,
            "card": "41",
            "pos": 5,
            "odds": "12",
            "btl": 12.0,
            "lto": 37
          },
          "l1": {
            "days": 14,
            "card": "78",
            "pos": 5,
            "odds": "20",
            "btl": 19.25,
            "lto": 17
          },
          "nty": 13.0,
          "open": 15.34,
          "tissue": "12/1",
          "rank": 7,
          "speed": 13.22,
          "track": 75,
          "distDelta": 200,
          "wtDelta": -0.5,
          "cls": "Class 4",
          "hcp": -6.0,
          "dp": 2,
          "days": 14,
          "tone": "plain"
        },
        {
          "cloth": 6,
          "draw": 6,
          "name": "VALLEDONNA",
          "filly": true,
          "trainer": "L V R Deshmukh",
          "jockey": "Antony Raj S",
          "age": "4y b f",
          "wt": 55.0,
          "al": "",
          "bnc": 31,
          "rtgCh": 1,
          "l2": {
            "days": 53,
            "card": "13",
            "pos": 4,
            "odds": "6",
            "btl": 7.0,
            "lto": 57
          },
          "l1": {
            "days": 27,
            "card": "59",
            "pos": 3,
            "odds": "15",
            "btl": 6.5,
            "lto": 69
          },
          "nty": 5.0,
          "open": 5.9,
          "tissue": "4/1",
          "rank": 3,
          "speed": 13.04,
          "track": 99,
          "distDelta": 200,
          "wtDelta": -1.5,
          "cls": "Class 4",
          "hcp": -6.0,
          "dp": -2,
          "days": 27,
          "tone": "pick"
        },
        {
          "cloth": 7,
          "draw": 3,
          "name": "SHUBHRAK",
          "filly": false,
          "trainer": "M F Ali Khan",
          "jockey": "Rafique Sk",
          "age": "7y b g",
          "wt": 52.5,
          "al": "",
          "bnc": 26,
          "rtgCh": 0,
          "l2": {
            "days": 19,
            "card": "71",
            "pos": 7,
            "odds": "20",
            "btl": 15.75,
            "lto": 15
          },
          "l1": {
            "days": 12,
            "card": "85",
            "pos": 8,
            "odds": "20",
            "btl": 13.5,
            "lto": 16
          },
          "nty": 34.0,
          "open": 40.12,
          "tissue": "33/1",
          "rank": 9,
          "speed": 13.41,
          "track": 0,
          "distDelta": 0,
          "wtDelta": 0.5,
          "cls": "Class 4",
          "hcp": -8.5,
          "dp": 4,
          "days": 12,
          "tone": "plain"
        },
        {
          "cloth": 8,
          "draw": 5,
          "name": "AMERICAN GANGSTER",
          "filly": false,
          "trainer": "Laxman Singh",
          "jockey": "D S Deora",
          "age": "4y b g",
          "wt": 52.0,
          "al": "",
          "bnc": 25,
          "rtgCh": 0,
          "l2": {
            "days": 41,
            "card": "27",
            "pos": 2,
            "odds": "3",
            "btl": 4.0,
            "lto": 79
          },
          "l1": {
            "days": 19,
            "card": "74",
            "pos": 4,
            "odds": "2.75",
            "btl": 8.25,
            "lto": 52
          },
          "nty": 7.0,
          "open": 8.26,
          "tissue": "6/1",
          "rank": 5,
          "speed": 13.11,
          "track": 99,
          "distDelta": 200,
          "wtDelta": -10.0,
          "cls": "Class 4",
          "hcp": -9.0,
          "dp": 0,
          "days": 19,
          "tone": "plain"
        },
        {
          "cloth": 9,
          "draw": 7,
          "name": "DECEMBER RAIN",
          "filly": true,
          "trainer": "Jasbir Singh",
          "jockey": "Arjun",
          "age": "5y b m",
          "wt": 52.0,
          "al": "",
          "bnc": 25,
          "rtgCh": 0,
          "l2": {
            "days": 175,
            "card": "44",
            "pos": 7,
            "odds": "20",
            "btl": 12.5,
            "lto": 26
          },
          "l1": {
            "days": 40,
            "card": "36",
            "pos": 4,
            "odds": "15",
            "btl": 9.25,
            "lto": 54
          },
          "nty": 21.0,
          "open": 24.78,
          "tissue": "20/1",
          "rank": 8,
          "speed": 12.98,
          "track": 45,
          "distDelta": 500,
          "wtDelta": -0.5,
          "cls": "Class 4",
          "hcp": -9.0,
          "dp": -6,
          "days": 40,
          "tone": "plain"
        },
        {
          "cloth": 10,
          "draw": 4,
          "name": "SEE MY ATTITUDE",
          "filly": true,
          "trainer": "M F Ali Khan",
          "jockey": "Surya Prakash",
          "age": "7y b m",
          "wt": 50.0,
          "al": "",
          "bnc": 21,
          "rtgCh": -1,
          "l2": {
            "days": 27,
            "card": "59",
            "pos": 8,
            "odds": "20",
            "btl": 20.75,
            "lto": -7
          },
          "l1": {
            "days": 14,
            "card": "81",
            "pos": 7,
            "odds": "20",
            "btl": 17.5,
            "lto": 10
          },
          "nty": 41.0,
          "open": 48.38,
          "tissue": "40/1",
          "rank": 10,
          "speed": 13.4,
          "track": 45,
          "distDelta": 400,
          "wtDelta": -5.0,
          "cls": "Class 4",
          "hcp": -11.0,
          "dp": 0,
          "days": 14,
          "tone": "plain"
        }
      ],
      "picks": {
        "win": 4,
        "plc": 1,
        "upset": 6,
        "lto": [
          2,
          4,
          6,
          1
        ],
        "hcpRtg": [
          1,
          2,
          3,
          4
        ],
        "speed": [
          1,
          2,
          4,
          9
        ]
      }
    }
  ]
} satisfies SheetMeeting;
